apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
              operator: In
              values:
                - flask-app
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: flask-app
          image: jesusod/flask-app
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          env:
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: MYSQL_PASSWORD
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: MYSQL_HOST
          - name: MYSQL_DB
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: MYSQL_DB
